# Generated by Django 3.0.10 on 2021-01-17 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lws', '0002_auto_20210117_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='MylistsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('webiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lws.WebinerListsModel')),
            ],
            options={
                'db_table': 'mylists',
            },
        ),
        migrations.AddConstraint(
            model_name='mylistsmodel',
            constraint=models.UniqueConstraint(fields=('user', 'webiner'), name='unique_registration'),
        ),
    ]
